logging:
  #pattern:
  #console: %d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
  level:
    root: INFO
---
server:
  port: 8080
  servlet:
    context-path: /heroServices
---
keycloak:
  enabled: true
  bearer-only: true
  auth-server-url: https://aplpre.favorita.ec/auth
  resource: SIR
  realm: CFAVORITA-SSO-INTRANET
  public-client: true
  principal-attribute: preferred_username
  #credentials:
  #secret = 11111111-1111-1111-1111-111111111111
  use-resource-role-mappings: true
  allowAnyHostname: true
---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test_cache_app;DB_CLOSE_ON_EXIT=FALSE;MODE=DB2
    username: SA
    password: 
    #initialization-mode: always
    #data: classpath:data.sql
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
  jpa:
    showSql: true
    properties:
      format_sql: false
      hibernate:
        hbm2ddl:
          auto: create-drop
        dialect: org.hibernate.dialect.H2Dialect
        id:
          batch_versioned_data: true
          new_generator_mappings: false # true for increment by 50 or (allocationSize property in mapping), false for increment one by one
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false